
name: api automation workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-automation-test:
    runs-on: ubuntu-latest


    steps:
      #download repo
      - uses: actions/checkout@v4
      #setup java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      #instal browser
      - name: setup chrome
        uses: browser-actions/setup-chrome@v1.5.0

        #setup gradlew
      - name: Setup Gradle
        run: chmod +x gradlew

        #execute gradle command for running cucumber test
      - name: execute test
        run: ./gradlew apiTest

        #Archive test result
      - name: Archive test result
        uses: actions/upload-artifact@v4.3.1
        if: always()
        with:
          name: Cucumber Report
          path: reports

        #Deploy to gitHub pages
      - name: Deploy to github page
        if: always()
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_DIR: reports
